mysql-user: 2022222974
spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/${mysql-user}?createDatabaseIfNotExist=true'
    username: ${mysql-user}
    password: ${mysql-user}

  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    org:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'